function(get_link_dependencies _target _listvar)
    set(_worklist ${${_listvar}})
    if (TARGET ${_target})
        list(APPEND _worklist ${_target})
        get_property(_dependencies GLOBAL PROPERTY GlobalTargetDepends${_target})
        foreach(_dependency IN LISTS _dependencies)
            if (NOT _dependency IN_LIST _worklist)
                get_link_dependencies(${_dependency} _worklist)
            endif()
        endforeach()
        set(${_listvar} "${_worklist}" PARENT_SCOPE)
    endif()
endfunction()

#function(get_dependencies _project_name _reg_exp)
#    get_link_dependencies(${_project_name} _deps)
#    foreach(_dep IN LISTS _deps)
#        get_target_property(_srcs ${_dep} SOURCES)
##        get_target_property(_src_dir ${_dep} SOURCE_DIR)
#        foreach(_src IN LISTS _srcs)
#            if(_src MATCHES ${_reg_exp})
#                list(APPEND _out_list "${_src}")
##                set(${_out_list} "${${_out_list}}" "${_src}" PARENT_SCOPE)
#            endif()
#        endforeach()
#    endforeach()
#endfunction()
